source=~/.config/mango/theme.conf
source=~/.config/mango/keybinds.conf
source=~/.config/mango/monitor.conf
source=~/.config/mango/autostart.conf

blur=1

blur_layer=1

blur_params_radius=8


layer_animations=1
layerrule=layer_name:^rofi$,animation_type_open:none,animation_type_close:none

