# ~/.config/mango/config.conf
source=~/.config/mango/theme.conf
source=~/.config/mango/keybinds.conf
source=~/.config/mango/monitor.conf
source=~/.config/mango/autostart.conf

# Blur the quickshell background
blur=1

# Enable blur specifically for status bars and menus (Quickshell)
blur_layer=1

# Optional: Tweak the frosted glass intensity (Default is 5)
blur_params_radius=8
